# Generated by Django 3.1 on 2021-10-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('word', models.CharField(max_length=10)),
                ('definition', models.CharField(max_length=40)),
                ('example', models.CharField(max_length=60)),
            ],
        ),
    ]
